[program:ntb_estoque_notafiscal_queue]
command=/opt/plesk/php/8.3/bin/php /var/www/vhost/valuable.com.br/ntb.bahiash.com.br/artisan queue:work --queue=notafiscal --tries=5 --timeout=600 --memory=512
# the user related to the server/domain
user=valuable.com.br_6wtymnf6tz9
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d
# optional logging:
stdout_logfile=/var/www/vhosts/valuable.com.br/logs/ntb.bahiash.com.br/notafiscal-queue-worker.log
