[program:ntb_estoque_reverb]
process_name=%(program_name)s_%(process_num)02d
command=/opt/plesk/php/8.4/bin/php /var/www/vhosts/valuable.com.br/ntb.bahiash.com.br/artisan reverb:start
user=valuable.com.br_6wtymnf6tz9
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
stdout_logfile=/var/www/vhosts/valuable.com.br/logs/ntb.bahiash.com.br/reverb-worker.log
