[program:ntb_estoque_produto_queue]
process_name=%(program_name)s_%(process_num)02d
command=/opt/plesk/php/8.4/bin/php /var/www/vhosts/valuable.com.br/ntb.bahiash.com.br/artisan queue:work --queue=produto --tries=5 --timeout=600 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=valuable.com.br_6wtymnf6tz9
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/vhosts/valuable.com.br/logs/ntb.bahiash.com.br/produto-queue-worker.log
stopwaitsecs=3600
